### ISSUE TITLE
Quando utilizar Herança, Polimorfismo e Encapsulamento?

### ISSUE THREAD

**Issue by g-roger** [g-roger/poo-java-exemplo#1]
Quando utilizar Herança, Polimorfismo e Encapsulamento? Justifique sobre.

**Comment by GustavoSwDaniel** [comment]
Encapsulamento é quando quero proteger os atributo das minha classe, na maioria das vezes os atributos serão privados, tendo acesso apenas por setters e getters.
Polimorfismo dever ser usando quando quero mudar o comportamento de um método.
Herança quando for necessário utilizar os atributos de uma classe em outra por exemplo: classe gerente herda os atributos da classe funcionário.
